# Always show source code snippets.
show-source = true

# Always show statistics
statistics = true

# Never enforce the following violations
ignore = ["D100", "D104", "D202", "D205", "D400", "D401", "E226", "E402", "E501", "W291", "W503"]

# These modules are built-in to Databricks PySpark
builtins = ["dbutils", "spark", "display"]
