name: MLOps Deployment

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
	strategy:
		matrix:
			python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Unit Tests
        run: |
			python src/tests/test_src.py

  training:
    name: Training
    runs-on: ubuntu-latest
	strategy:
		matrix:
			python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Training
        run: |
			python src/model/train.py
